print('Hello')
print("I'm studying python")
print('I\'m studying  Python')
print("I'm studying Python")
print("and I'm having fun")
print("I'm studying Python", "and having fun")
print("I'm studying Python \nand having  fun")